In [4]:
(lambda a, b: a+b)(53, 23)

76

In [1]:
def add(a, b):
    return a+b

In [3]:
add(47747, 3737)

51484

In [5]:
add_lambda = lambda a, b: a+b

In [6]:
add_lambda(12, 18)

30

In [10]:
fruits = ['orange', 'mango', 'apple', 'peach', 'watermelon', 'dragenfruit']

In [11]:
len(fruits)

6

In [14]:
fruits[-1]

'dragenfruit'

In [16]:
len(fruits[-1])

11

In [19]:
for i in fruits:
    print(i, len(i))

orange 6
mango 5
apple 5
peach 5
watermelon 10
dragenfruit 11


In [20]:
fruits_len = []

for f in fruits:
    fruits_len.append(len(f))

In [21]:
fruits_len

[6, 5, 5, 5, 10, 11]

In [22]:
## map function

In [23]:
fruits = ['orange', 'mango', 'apple', 'peach', 'watermelon', 'dragenfruit']

In [24]:
len

<function len(obj, /)>

In [26]:
list(map(len, fruits))

[6, 5, 5, 5, 10, 11]

In [31]:
fruits_changed = ['orange', 'mango', 'apple', ['string', 3], 'peach', 'watermelon', 'dragenfruit']

In [32]:
list(map(len, fruits_changed))

[6, 5, 5, 2, 5, 10, 11]

In [34]:
len(fruits_changed[3])

2

In [35]:
max("orange")

'r'

In [36]:
def first_char(s):
    return s[0]

In [38]:
first_char('ahamd')

'a'

In [40]:
list(map(first_char, fruits))

['o', 'm', 'a', 'p', 'w', 'd']

In [41]:
fruits

['orange', 'mango', 'apple', 'peach', 'watermelon', 'dragenfruit']

In [42]:
first_char_l = lambda s: s[0]

list(map(first_char_l, fruits))

['o', 'm', 'a', 'p', 'w', 'd']

In [43]:
list(map(lambda s: s[0], fruits))

['o', 'm', 'a', 'p', 'w', 'd']

In [52]:
def MAP(function, seq):
    output_list = []

    for el in seq:
        output_list.append(function(el))

    return output_list

    

In [53]:
list(map(len, fruits))

[6, 5, 5, 5, 10, 11]

In [54]:
MAP(len, fruits)

[6, 5, 5, 5, 10, 11]

In [57]:
def MAP(function, seq):
    return [function(el) for el in seq]


In [58]:
MAP(len, fruits)

[6, 5, 5, 5, 10, 11]

In [59]:
MAP = lambda fun, seq: [fun(el) for el in seq]

In [60]:
MAP(len, fruits)

[6, 5, 5, 5, 10, 11]

In [61]:
numbers = [53, 23, 54, 23, 66, 34, 10]

In [62]:
def add_number(n):
    return n+5

In [64]:
add_number(100)

105

In [69]:
tuple(map(add_number, numbers))

(58, 28, 59, 28, 71, 39, 15)

In [68]:
numbers

[53, 23, 54, 23, 66, 34, 10]

In [70]:
def lessthan(n):
    if n < 50:
        return True
    else:
        return False

In [72]:
lessthan(60)

False

In [74]:
list(filter(lessthan, numbers))

[23, 23, 34, 10]

In [75]:
def is_even(n):
    if n%2 == 0:
        return True
    else:
        return False

In [77]:
list(filter(is_even, numbers))

[54, 66, 34, 10]

In [78]:
numbers

[53, 23, 54, 23, 66, 34, 10]

In [ ]:
3000000/1024   ## Byte --> KB

2929.6875

In [ ]:
2929.6875/1024   ## KB ---> MB

2.86102294921875

In [82]:
age = 30

In [85]:
combined_list = [124, 53, 233, 54.3, 23.675, 'ahmad', 'salman', True, False]

In [92]:
def is_int(n):
    return isinstance(n, int)

In [94]:
is_int(20.8)

False

In [95]:
tuple(filter(is_int,  combined_list))

(124, 53, 233, True, False)

In [98]:
isinstance(True, int)

True

In [101]:
def is_str(n):
    return isinstance(n, str)

In [102]:
list(filter(is_str, combined_list))

['ahmad', 'salman']

In [1]:
l = [23, 53, 23, 64]

In [ ]:
def addition(total, current_element):
    return total + current_element

In [3]:
total = 0

In [7]:
total = addition(total, 10)

In [8]:
total = addition(total, 20)

In [10]:
total = addition(total, 30)

In [11]:
total 

60

In [12]:
def addition(total, current_element):
    return total + current_element

In [13]:
l = [1, 2, 3, 4, 5, 6, 7, 8]

In [17]:
import functools as tool

In [19]:
from functools import reduce

In [20]:
reduce

<function _functools.reduce>

In [21]:
reduce(addition, l)

36

In [22]:
reduce(lambda tot, el: tot+el,  l)

36

In [23]:
sum(l)

36

In [24]:
fruits = ['orange', 'mango', 'apple', 'peach', 'watermelon', 'dragenfruit']

In [25]:
reduce(lambda comb, cstr: comb+cstr, fruits)

'orangemangoapplepeachwatermelondragenfruit'

In [26]:
fruits

['orange', 'mango', 'apple', 'peach', 'watermelon', 'dragenfruit']

In [28]:
list(enumerate(fruits))

[(0, 'orange'),
 (1, 'mango'),
 (2, 'apple'),
 (3, 'peach'),
 (4, 'watermelon'),
 (5, 'dragenfruit')]

In [32]:
i, f = (0, 'orange')

In [35]:
for i, f in enumerate(fruits):
    print(f"{f} is stored at {i} location")

orange is stored at 0 location
mango is stored at 1 location
apple is stored at 2 location
peach is stored at 3 location
watermelon is stored at 4 location
dragenfruit is stored at 5 location


In [37]:
list(enumerate((23, 64, 23, 12)))

[(0, 23), (1, 64), (2, 23), (3, 12)]

In [38]:
list(enumerate("STRING"))

[(0, 'S'), (1, 'T'), (2, 'R'), (3, 'I'), (4, 'N'), (5, 'G')]

In [39]:
list(enumerate({'name':'ali', 'age':23}))

[(0, 'name'), (1, 'age')]

In [40]:
d = {'name':'ali', 'age':23}

for k in d:
    print(k)

name
age


In [42]:
names = ['ali', 'kamran', 'salman', 'ahmad', 'usman']
marks = [79, 100, 96, 30, 86]

In [45]:
dict(zip(names, marks))

{'ali': 79, 'kamran': 100, 'salman': 96, 'ahmad': 30, 'usman': 86}

In [48]:
any([False, False, False, False])

False

In [51]:
any(['', 0, 0.0, False])

False

In [52]:
any(['a', 0, 0.0 ])

True

In [55]:
any([20!=20, 'string'!="string", 3.5!=3.5])

False

In [ ]:
20!=20 or 'string'!="string" or 3.5!=3.5

In [56]:
import numpy as np

In [58]:
arr = np.arange(0, 50)

In [59]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [60]:
arr[arr<=25]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

In [61]:
arr<=25

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [62]:
all([True, True, True])

True

In [63]:
all([False, True, True, True, True])

False